import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Header from "@/app/components/layout/Header"
import './globals.css'

const roboto = Roboto({ subsets: ['latin'], weight:['400','500','700','900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="vi">
      <body className={roboto.className}>
        <Header />
        <main className='max-w-6xl mx-auto p-4'>
        {children}
        </main>
      </body>
    </html>
  )
}
